'use strict';
// sql template autogenerated by gen-db-migrates

var async = require('async')
var dbm;
var type;
var seed;

/**
* We receive the dbmigrate dependency from dbmigrate initially.
* This enables us to not have to rely on NODE_PATH.
*/
exports.setup = function(options, seedLink) {
  dbm = options.dbmigrate;
  type = dbm.dataType;
  seed = seedLink;
};

exports.up = function (db, callback) {
  async.series([
    (cb) => db.createTable('bonusprogram', {
    columns: {
    "id": {
        "type": "string",
        "primaryKey": true
    },
    "name": {
        "type": "string"
    },
    "adapter": {
        "type": "string",
        "unique": true
    },
    "exchangeRate": {
        "type": "real"
    },
    "coveragePercentage": {
        "type": "real"
    },
    "decimals": {
        "type": "real"
    },
    "sortOrder": {
        "type": "real"
    },
    "description": {
        "type": "string"
    },
    "iconLink": {
        "type": "string"
    },
    "detailInfoLink": {
        "type": "string"
    },
    "enable": {
        "type": "boolean"
    },
    "automaticUserRegistration": {
        "type": "boolean"
    },
    "customData": {
        "type": "json"
    },
    "createdAt": {
        "type": "bigint"
    },
    "updatedAt": {
        "type": "bigint"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('city', {
    columns: {
    "id": {
        "type": "string",
        "primaryKey": true
    },
    "externalId": {
        "type": "string"
    },
    "name": {
        "type": "string"
    },
    "isDeleted": {
        "type": "boolean"
    },
    "customData": {
        "type": "json"
    },
    "createdAt": {
        "type": "bigint"
    },
    "updatedAt": {
        "type": "bigint"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('dish', {
    columns: {
    "id": {
        "type": "string",
        "primaryKey": true
    },
    "rmsId": {
        "type": "string"
    },
    "additionalInfo": {
        "type": "string",
        "notNull": false
    },
    "code": {
        "type": "string",
        "notNull": false
    },
    "description": {
        "type": "string",
        "notNull": false
    },
    "ingredients": {
        "type": "string",
        "notNull": false
    },
    "name": {
        "type": "string"
    },
    "seoDescription": {
        "type": "string",
        "notNull": false
    },
    "seoKeywords": {
        "type": "string",
        "notNull": false
    },
    "seoText": {
        "type": "string",
        "notNull": false
    },
    "seoTitle": {
        "type": "string",
        "notNull": false
    },
    "carbohydrateAmount": {
        "type": "real"
    },
    "carbohydrateFullAmount": {
        "type": "real",
        "notNull": false
    },
    "energyAmount": {
        "type": "real",
        "notNull": false
    },
    "energyFullAmount": {
        "type": "real",
        "notNull": false
    },
    "fatAmount": {
        "type": "real",
        "notNull": false
    },
    "fatFullAmount": {
        "type": "real",
        "notNull": false
    },
    "fiberAmount": {
        "type": "real",
        "notNull": false
    },
    "fiberFullAmount": {
        "type": "real",
        "notNull": false
    },
    "groupId": {
        "type": "string",
        "notNull": false
    },
    "measureUnit": {
        "type": "string",
        "notNull": false
    },
    "price": {
        "type": "real"
    },
    "productCategoryId": {
        "type": "string",
        "notNull": false
    },
    "type": {
        "type": "string"
    },
    "weight": {
        "type": "real",
        "notNull": false
    },
    "sortOrder": {
        "type": "real"
    },
    "isDeleted": {
        "type": "boolean"
    },
    "isModificable": {
        "type": "boolean"
    },
    "modifiers": {
        "type": "json"
    },
    "tags": {
        "type": "json"
    },
    "balance": {
        "type": "real",
        "defaultValue": -1
    },
    "slug": {
        "type": "string"
    },
    "concept": {
        "type": "string"
    },
    "hash": {
        "type": "string"
    },
    "visible": {
        "type": "boolean"
    },
    "modifier": {
        "type": "boolean"
    },
    "promo": {
        "type": "boolean"
    },
    "worktime": {
        "type": "json"
    },
    "customData": {
        "type": "json"
    },
    "createdAt": {
        "type": "bigint"
    },
    "updatedAt": {
        "type": "bigint"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('group', {
    columns: {
    "id": {
        "type": "string",
        "primaryKey": true
    },
    "rmsId": {
        "type": "string"
    },
    "additionalInfo": {
        "type": "string",
        "notNull": false
    },
    "code": {
        "type": "string",
        "notNull": false
    },
    "description": {
        "type": "string",
        "notNull": false
    },
    "isDeleted": {
        "type": "boolean"
    },
    "name": {
        "type": "string"
    },
    "seoDescription": {
        "type": "string",
        "notNull": false
    },
    "seoKeywords": {
        "type": "string",
        "notNull": false
    },
    "seoText": {
        "type": "string",
        "notNull": false
    },
    "seoTitle": {
        "type": "string",
        "notNull": false
    },
    "sortOrder": {
        "type": "real"
    },
    "icon": {
        "type": "string",
        "notNull": false
    },
    "slug": {
        "type": "string"
    },
    "concept": {
        "type": "string"
    },
    "visible": {
        "type": "boolean"
    },
    "modifier": {
        "type": "boolean"
    },
    "promo": {
        "type": "boolean"
    },
    "worktime": {
        "type": "json"
    },
    "customData": {
        "type": "json"
    },
    "createdAt": {
        "type": "bigint"
    },
    "updatedAt": {
        "type": "bigint"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('maintenance', {
    columns: {
    "id": {
        "type": "string",
        "primaryKey": true
    },
    "title": {
        "type": "string"
    },
    "description": {
        "type": "string"
    },
    "enable": {
        "type": "boolean",
        "defaultValue": true
    },
    "worktime": {
        "type": "json"
    },
    "startDate": {
        "type": "string"
    },
    "stopDate": {
        "type": "string"
    },
    "createdAt": {
        "type": "bigint"
    },
    "updatedAt": {
        "type": "bigint"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('mediafile', {
    columns: {
    "id": {
        "type": "string",
        "primaryKey": true
    },
    "images": {
        "type": "json"
    },
    "original": {
        "type": "string"
    },
    "sortOrder": {
        "type": "real"
    },
    "uploadDate": {
        "type": "string"
    },
    "createdAt": {
        "type": "bigint"
    },
    "updatedAt": {
        "type": "bigint"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('onetimepassword', {
    columns: {
    "id": {
        "type": "int",
        "autoIncrement": true,
        "primaryKey": true
    },
    "login": {
        "type": "string"
    },
    "password": {
        "type": "string"
    },
    "expires": {
        "type": "real"
    },
    "createdAt": {
        "type": "bigint"
    },
    "updatedAt": {
        "type": "bigint"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('order', {
    columns: {
    "id": {
        "type": "string",
        "primaryKey": true
    },
    "shortId": {
        "type": "string"
    },
    "concept": {
        "type": "string"
    },
    "isMixedConcept": {
        "type": "boolean"
    },
    "paymentMethodTitle": {
        "type": "string"
    },
    "paid": {
        "type": "boolean",
        "defaultValue": false
    },
    "isPaymentPromise": {
        "type": "boolean",
        "defaultValue": true
    },
    "promotionState": {
        "type": "json"
    },
    "isPromoted": {
        "type": "boolean"
    },
    "dishesCount": {
        "type": "real"
    },
    "uniqueDishes": {
        "type": "real"
    },
    "modifiers": {
        "type": "json"
    },
    "customer": {
        "type": "json"
    },
    "address": {
        "type": "json"
    },
    "comment": {
        "type": "string"
    },
    "personsCount": {
        "type": "string"
    },
    "date": {
        "type": "string"
    },
    "problem": {
        "type": "boolean",
        "defaultValue": false
    },
    "rmsDelivered": {
        "type": "boolean",
        "defaultValue": false
    },
    "rmsId": {
        "type": "string"
    },
    "rmsOrderNumber": {
        "type": "string"
    },
    "rmsOrderData": {
        "type": "json"
    },
    "rmsDeliveryDate": {
        "type": "string"
    },
    "rmsErrorMessage": {
        "type": "string"
    },
    "rmsErrorCode": {
        "type": "string"
    },
    "rmsStatusCode": {
        "type": "string"
    },
    "deliveryStatus": {
        "type": "string"
    },
    "selfService": {
        "type": "boolean",
        "defaultValue": false
    },
    "delivery": {
        "type": "json"
    },
    "deliveryDescription": {
        "type": "string",
        "notNull": false
    },
    "message": {
        "type": "string"
    },
    "deliveryCost": {
        "type": "real",
        "defaultValue": 0
    },
    "totalWeight": {
        "type": "real",
        "defaultValue": 0
    },
    "trifleFrom": {
        "type": "real",
        "defaultValue": 0
    },
    "bonusesTotal": {
        "type": "real",
        "defaultValue": 0
    },
    "spendBonus": {
        "type": "json"
    },
    "total": {
        "type": "real",
        "defaultValue": 0
    },
    "basketTotal": {
        "type": "real",
        "defaultValue": 0
    },
    "orderTotal": {
        "type": "real",
        "defaultValue": 0
    },
    "discountTotal": {
        "type": "real",
        "defaultValue": 0
    },
    "orderDate": {
        "type": "string"
    },
    "deviceId": {
        "type": "string"
    },
    "customData": {
        "type": "json"
    },
    "createdAt": {
        "type": "bigint"
    },
    "updatedAt": {
        "type": "bigint"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('orderdish', {
    columns: {
    "id": {
        "type": "int",
        "autoIncrement": true,
        "primaryKey": true
    },
    "amount": {
        "type": "real"
    },
    "modifiers": {
        "type": "json"
    },
    "uniqueItems": {
        "type": "real"
    },
    "itemTotal": {
        "type": "real"
    },
    "itemTotalBeforeDiscount": {
        "type": "real"
    },
    "discountTotal": {
        "type": "real"
    },
    "discountType": {
        "type": "string"
    },
    "discountAmount": {
        "type": "real"
    },
    "discountMessage": {
        "type": "string"
    },
    "comment": {
        "type": "string"
    },
    "addedBy": {
        "type": "string",
        "defaultValue": "user"
    },
    "weight": {
        "type": "real"
    },
    "totalWeight": {
        "type": "real"
    },
    "createdAt": {
        "type": "bigint"
    },
    "updatedAt": {
        "type": "bigint"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('paymentdocument', {
    columns: {
    "id": {
        "type": "string",
        "primaryKey": true
    },
    "paymentId": {
        "type": "string"
    },
    "externalId": {
        "type": "string"
    },
    "originModel": {
        "type": "string"
    },
    "amount": {
        "type": "real"
    },
    "paid": {
        "type": "boolean",
        "defaultValue": false
    },
    "status": {
        "type": "string",
        "defaultValue": "NEW"
    },
    "comment": {
        "type": "string"
    },
    "redirectLink": {
        "type": "string"
    },
    "error": {
        "type": "string"
    },
    "data": {
        "type": "json"
    },
    "createdAt": {
        "type": "bigint"
    },
    "updatedAt": {
        "type": "bigint"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('paymentmethod', {
    columns: {
    "id": {
        "type": "string",
        "primaryKey": true
    },
    "externalId": {
        "type": "string",
        "notNull": false
    },
    "title": {
        "type": "string"
    },
    "type": {
        "type": "string"
    },
    "isCash": {
        "type": "boolean"
    },
    "adapter": {
        "type": "string",
        "unique": true
    },
    "sortOrder": {
        "type": "real"
    },
    "description": {
        "type": "string"
    },
    "enable": {
        "type": "boolean"
    },
    "createdAt": {
        "type": "bigint"
    },
    "updatedAt": {
        "type": "bigint"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('place', {
    columns: {
    "id": {
        "type": "string",
        "primaryKey": true
    },
    "title": {
        "type": "string"
    },
    "address": {
        "type": "string"
    },
    "order": {
        "type": "real"
    },
    "phone": {
        "type": "string"
    },
    "enable": {
        "type": "boolean"
    },
    "worktime": {
        "type": "json"
    },
    "isPickupPoint": {
        "type": "boolean"
    },
    "isCookingPoint": {
        "type": "boolean"
    },
    "isSalePoint": {
        "type": "boolean"
    },
    "customData": {
        "type": "json"
    },
    "createdAt": {
        "type": "bigint"
    },
    "updatedAt": {
        "type": "bigint"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('promotion', {
    columns: {
    "id": {
        "type": "string",
        "unique": true,
        "primaryKey": true
    },
    "externalId": {
        "type": "string",
        "unique": true
    },
    "configDiscount": {
        "type": "json"
    },
    "createdByUser": {
        "type": "boolean"
    },
    "name": {
        "type": "string"
    },
    "concept": {
        "type": "json"
    },
    "sortOrder": {
        "type": "real"
    },
    "description": {
        "type": "string"
    },
    "isPublic": {
        "type": "boolean"
    },
    "isJoint": {
        "type": "boolean"
    },
    "productCategoryPromotions": {
        "type": "json"
    },
    "enable": {
        "type": "boolean"
    },
    "isDeleted": {
        "type": "boolean"
    },
    "hash": {
        "type": "string"
    },
    "worktime": {
        "type": "json"
    },
    "createdAt": {
        "type": "bigint"
    },
    "updatedAt": {
        "type": "bigint"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('settings', {
    columns: {
    "id": {
        "type": "int",
        "autoIncrement": true,
        "primaryKey": true
    },
    "key": {
        "type": "string",
        "unique": true
    },
    "description": {
        "type": "string"
    },
    "value": {
        "type": "json"
    },
    "section": {
        "type": "string"
    },
    "from": {
        "type": "string"
    },
    "readOnly": {
        "type": "boolean"
    },
    "createdAt": {
        "type": "bigint"
    },
    "updatedAt": {
        "type": "bigint"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('street', {
    columns: {
    "id": {
        "type": "string",
        "primaryKey": true
    },
    "externalId": {
        "type": "string"
    },
    "name": {
        "type": "string"
    },
    "hash": {
        "type": "string"
    },
    "isDeleted": {
        "type": "boolean"
    },
    "customData": {
        "type": "json"
    },
    "createdAt": {
        "type": "bigint"
    },
    "updatedAt": {
        "type": "bigint"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('user', {
    columns: {
    "id": {
        "type": "string",
        "unique": true,
        "primaryKey": true
    },
    "login": {
        "type": "string"
    },
    "firstName": {
        "type": "string",
        "notNull": false
    },
    "lastName": {
        "type": "string",
        "notNull": false
    },
    "email": {
        "type": "string"
    },
    "phone": {
        "type": "json"
    },
    "birthday": {
        "type": "string"
    },
    "verified": {
        "type": "boolean"
    },
    "allRequiredCustomFieldsAreFilled": {
        "type": "boolean"
    },
    "passwordHash": {
        "type": "string",
        "notNull": false
    },
    "lastPasswordChange": {
        "type": "real"
    },
    "temporaryCode": {
        "type": "string",
        "notNull": false
    },
    "orderCount": {
        "type": "real"
    },
    "isDeleted": {
        "type": "boolean"
    },
    "customFields": {
        "type": "json"
    },
    "customData": {
        "type": "json"
    },
    "createdAt": {
        "type": "bigint"
    },
    "updatedAt": {
        "type": "bigint"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('userbonusprogram', {
    columns: {
    "id": {
        "type": "string",
        "primaryKey": true
    },
    "balance": {
        "type": "real"
    },
    "isDeleted": {
        "type": "boolean"
    },
    "isActive": {
        "type": "boolean"
    },
    "syncedToTime": {
        "type": "string"
    },
    "customData": {
        "type": "json"
    },
    "createdAt": {
        "type": "bigint"
    },
    "updatedAt": {
        "type": "bigint"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('userbonustransaction', {
    columns: {
    "id": {
        "type": "string",
        "primaryKey": true
    },
    "externalId": {
        "type": "string"
    },
    "isNegative": {
        "type": "boolean"
    },
    "group": {
        "type": "string"
    },
    "amount": {
        "type": "real"
    },
    "balanceAfter": {
        "type": "real"
    },
    "isDeleted": {
        "type": "boolean"
    },
    "isStable": {
        "type": "boolean"
    },
    "time": {
        "type": "string"
    },
    "customData": {
        "type": "json"
    },
    "createdAt": {
        "type": "bigint"
    },
    "updatedAt": {
        "type": "bigint"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('userdevice', {
    columns: {
    "id": {
        "type": "string",
        "primaryKey": true
    },
    "name": {
        "type": "string"
    },
    "userAgent": {
        "type": "string"
    },
    "isLogined": {
        "type": "boolean"
    },
    "lastIP": {
        "type": "string"
    },
    "loginTime": {
        "type": "real"
    },
    "lastActivity": {
        "type": "real"
    },
    "sessionId": {
        "type": "string",
        "notNull": false
    },
    "customData": {
        "type": "json"
    },
    "createdAt": {
        "type": "bigint"
    },
    "updatedAt": {
        "type": "bigint"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('userlocation', {
    columns: {
    "id": {
        "type": "string",
        "primaryKey": true
    },
    "name": {
        "type": "string",
        "notNull": false
    },
    "city": {
        "type": "string",
        "notNull": false
    },
    "home": {
        "type": "string",
        "notNull": false
    },
    "housing": {
        "type": "string",
        "notNull": false
    },
    "index": {
        "type": "string",
        "notNull": false
    },
    "entrance": {
        "type": "string",
        "notNull": false
    },
    "floor": {
        "type": "string",
        "notNull": false
    },
    "apartment": {
        "type": "string",
        "notNull": false
    },
    "doorphone": {
        "type": "string",
        "notNull": false
    },
    "isDefault": {
        "type": "boolean"
    },
    "comment": {
        "type": "string",
        "notNull": false
    },
    "customData": {
        "type": "json"
    },
    "createdAt": {
        "type": "bigint"
    },
    "updatedAt": {
        "type": "bigint"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('userorderhistory', {
    columns: {
    "id": {
        "type": "string",
        "primaryKey": true
    },
    "uniqueItems": {
        "type": "real"
    },
    "orderTotal": {
        "type": "real"
    },
    "total": {
        "type": "real"
    },
    "order": {
        "type": "json"
    },
    "discountTotal": {
        "type": "real"
    },
    "comment": {
        "type": "string"
    },
    "totalWeight": {
        "type": "real"
    },
    "createdAt": {
        "type": "bigint"
    },
    "updatedAt": {
        "type": "bigint"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('dish_images__mediafile_dish', {
    columns: {
    "id": {
        "type": "int",
        "notNull": true,
        "autoIncrement": true
    },
    "dish_images": {
        "type": "string"
    },
    "mediafile_dish": {
        "type": "string"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('group_dishes__dish_parentGroup', {
    columns: {
    "id": {
        "type": "int",
        "notNull": true,
        "autoIncrement": true
    },
    "group_dishes": {
        "type": "string"
    },
    "dish_parentGroup": {
        "type": "string"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('group_childGroups__group_parentGroup', {
    columns: {
    "id": {
        "type": "int",
        "notNull": true,
        "autoIncrement": true
    },
    "group_childGroups": {
        "type": "string"
    },
    "group_parentGroup": {
        "type": "string"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('group_images__mediafile_group', {
    columns: {
    "id": {
        "type": "int",
        "notNull": true,
        "autoIncrement": true
    },
    "group_images": {
        "type": "string"
    },
    "mediafile_group": {
        "type": "string"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('order_dishes__OrderDish_order', {
    columns: {
    "id": {
        "type": "int",
        "notNull": true,
        "autoIncrement": true
    },
    "order_dishes": {
        "type": "string"
    },
    "OrderDish_order": {
        "type": "string"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('user_favorites__dish_id', {
    columns: {
    "id": {
        "type": "int",
        "notNull": true,
        "autoIncrement": true
    },
    "user_favorites": {
        "type": "string"
    },
    "dish_id": {
        "type": "string"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('user_bonusProgram__userbonusprogram_user', {
    columns: {
    "id": {
        "type": "int",
        "notNull": true,
        "autoIncrement": true
    },
    "user_bonusProgram": {
        "type": "string"
    },
    "userbonusprogram_user": {
        "type": "string"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('user_history__UserOrderHistory_user', {
    columns: {
    "id": {
        "type": "int",
        "notNull": true,
        "autoIncrement": true
    },
    "user_history": {
        "type": "string"
    },
    "UserOrderHistory_user": {
        "type": "string"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('user_locations__UserLocation_user', {
    columns: {
    "id": {
        "type": "int",
        "notNull": true,
        "autoIncrement": true
    },
    "user_locations": {
        "type": "string"
    },
    "UserLocation_user": {
        "type": "string"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('user_devices__UserDevice_user', {
    columns: {
    "id": {
        "type": "int",
        "notNull": true,
        "autoIncrement": true
    },
    "user_devices": {
        "type": "string"
    },
    "UserDevice_user": {
        "type": "string"
    }
},
    ifNotExists: true
  }, cb),

  ], callback);
}

exports.down = function(db) {
  return null;
};

exports._meta = {
  "version": 1
};
