export declare const ORDER_STATE_TRANSITIONS: Record<string, string[]>;
export declare const ORDER_OPERATOR_ALLOWED_TARGET_STATES: string[];
export declare const ORDER_COMPLETED_STATES: string[];
export declare const ORDER_PRE_ORDER_FILTERED_STATES: string[];
export declare const ORDER_KITCHEN_PROGRESS_STATES: string[];
export declare const ORDER_KANBAN_DEFAULT_COMPLETED_WINDOW_HOURS = 24;
export declare const ORDER_KANBAN_DEFAULT_NEW_WINDOW_MINUTES = 15;
export declare function isOperatorUser(user: any): boolean;
export declare function isValidOrderState(state: unknown): boolean;
export declare function isCompletedOrderState(state: unknown): boolean;
export declare function isPreOrderFilteredState(state: unknown): boolean;
export declare function isKitchenProgressOrderState(state: unknown): boolean;
export declare function getAllowedOrderTransitions(state: string): string[];
export declare function getAllowedOrderTransitionsByRole(state: string, operatorLimited: boolean): string[];
