name: Run tests
on:
  push:
    branches-ignore:
      - master
      - alpha
      - test-with-postgres
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm run test:init 2>&1 || true  npm run test