'use strict';
// sql template autogenerated by gen-db-migrates

var async = require('async');
var dbm;
var type;
var seed;

/**
 * We receive the dbmigrate dependency from dbmigrate initially.
 * This enables us to not have to rely on NODE_PATH.
 */
exports.setup = function(options, seedLink) {
  dbm = options.dbmigrate;
  type = dbm.dataType;
  seed = seedLink;
};

exports.up = function (db, callback) {
  async.series([
      (cb) => db.renameColumn('order', 'deliveryStatus', 'rmsOrderStatus', cb),
      (cb) => db.createTable('dish_recommendedForGroup__group_recommendedDishes', {
        columns: {
        "id": {
            "type": "serial",
            "autoIncrement": true,
            "primaryKey": true
        },
        "group_recommendedDishes": {
            "type": "text"
        },
        "dish_recommendedForGroup": {
            "type": "text"
        }
    }, ifNotExists: true}, cb),
      (cb) => db.addColumn('city', 'slug', { type: 'string' }, cb),
      (cb) => db.addColumn('city', 'boundingBox', { type: 'json' }, cb),
  ], callback);
};

exports.down = function(db, callback) {
  async.series([
      (cb) => db.removeColumn('city', 'slug', cb),
      (cb) => db.removeColumn('city', 'boundingBox', cb)
  ], callback);
};

exports._meta = {
  "version": 1
};
